version: '3'
services: 
  e2e:
    image: cypress
    build: .
    container_name: cypress
    command: npx cypress run
    volumes: 
      - /Users/imagemaker/Downloads/report/:/Users/imagemaker/Downloads/report/